import '../styles/globals.css'
import type { AppProps } from 'next/app'
import Head from 'next/head'
// import {store} from '../store/store'
// import { Provider } from 'react-redux'

export default function App({ Component, pageProps }: AppProps) {
  return(
    <>
    <Head>
        <title>Renshop</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/Renshop.svg" />
      </Head>
      <Component {...pageProps} />
    </>
  ) 
}
